# Site settings
title: CAITLYN KODRIC
email: cmykodri@edu.uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  Caitlyn Kodric personal portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.caitlynkodric.com" # the base hostname & protocol for your site
twitter_username: CAITLYNKODRIC
github_username:  caitlynkodric

# Build settings
markdown: kramdown

gems: ['jekyll-github-metadata']